
 platform :ios, '9.0'

target 'ServicesApp' do

  use_frameworks!

pod 'MaterialComponents/TextControls+FilledTextAreas'
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'MaterialComponents/TextControls+OutlinedTextAreas'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'InAppNotify'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Storage'
pod 'lottie-ios'
pod 'IQKeyboardManagerSwift'
pod 'AMKeyboardFrameTracker'


end
